### ISSUE TITLE
an SDP problem: ArgumentError: invalid index: nothing of type Nothing

### ISSUE THREAD

**Issue by markerror** [oxfordcontrol/COSMO.jl#103]
I meeting the following problem when solving an SDP problem with 119 decision variables and 11 linear matrix inequlities.

ArgumentError: invalid index: nothing of type Nothing

Stacktrace:
 [1] to_index(::Nothing) at .\indices.jl:270
 [2] to_index(::Array{Int64,1}, ::Nothing) at .\indices.jl:247
 [3] to_indices at .\indices.jl:298 [inlined]
 [4] to_indices at .\indices.jl:295 [inlined]
 [5] getindex at .\abstractarray.jl:981 [inlined]

This solver along with JuMP works well for some samll matrices. Yet, when some SparsePsdCone  constraint (S^21*21) is added, this problem occurrs.

**Comment by migarstka** [comment]
Hi Mark,

thank you for your message. It is difficult for me to see what went wrong based on the Stacktrace that you posted (the stacktrace doesn't contain any line from the COSMO.jl package). Could you post a minimal working example so that I can reproduce the error?

**Comment by markerror** [comment]
Hi, migarstka,

Thank you! I meet a similar problem. It's list as follows.

# Model
model = A JuMP Model

Minimization problem with:

Variables: 96

Objective function type: VariableRef
`GenericAffExpr{Float64,VariableRef}`-in-`MathOptInterface.LessThan{Float64}`: 2 constraints
`Array{GenericAffExpr{Float64,VariableRef},1}`-in-`MathOptInterface.PositiveSemidefiniteConeSquare`: 12 constraints

Model mode: AUTOMATIC

CachingOptimizer state: ATTACHED_OPTIMIZER

Solver name: COSMO

Note: `The model has been successfully solved by the Mosektools with JuMP.` 

# Some key SDConstraints
    for i=1:g
        for j=1:g
            for k=1:gk
                Omg[i,j,k]=[Omg11[i,j,k] Omg12[i,j,k] Omg13[i,j,k] zeros(n0,n) zeros(n0,n) zeros(n0,1);
                    Omg12[i,j,k]' Omg22[i,j,k] Omg23[i,k] zeros(n,n) alpha*(eye(n)-kron(e[i],E))' (F*E*XX)';
                    Omg13[i,j,k]' Omg23[i,k]' Omg33[i,k] Omg34[k] zeros(n,n)  zeros(n,1);
                    zeros(n,n0) zeros(n,n) Omg34[k]' -R zeros(n,n) zeros(n,1);
                    zeros(n,n0) alpha*(eye(n)-kron(e[i],E)) zeros(n,n) zeros(n,n) -WW[i] zeros(n,1);
                    zeros(1,n0) F*E*XX zeros(1,n) zeros(1,n) zeros(1,n) J0[i]-2];
                    
                    @SDconstraint(model,Omg[i,j,k]+Omg[j,i,k]<=0)
            end
        end
    end

# Errors

**ArgumentError:` invalid index: nothing of type Nothing** 

Stacktrace:

> [1] to_index(::Nothing) at .\indices.jl:270
 
> [2] to_index(::Array{Int64,1}, ::Nothing) at .\indices.jl:247
 
> [3] to_indices at .\indices.jl:298 [inlined]
 
> [4] to_indices at .\indices.jl:295 [inlined]
 
> [5] getindex at .\abstractarray.jl:981 [inlined]
 
> [6] add_entries!(::Array{Int64,1}, ::Array{Int64,1}, ::Array{COSMO.AbstractConvexSet{Float64},1}, ::Int64, ::SparseArrays.SparseMatrixCSC{Float64,Int64}, ::SparseArrays.SparseVector{Float64,Int64}, ::UnitRange{Int64}, ::Int64, ::Int64, ::Int64, ::Array{COSMO.SparsityPattern,1}, ::COSMO.Nonnegatives{Float64}, ::Int64, ::Dict{Int64,Int64}) at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\COSMO\4kAZK\src\transformations.jl:243
 
> [7] augment_clique_based!(::COSMO.Workspace{Float64}) at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\COSMO\4kAZK\src\transformations.jl:189
 
> [8] chordal_decomposition!(::COSMO.Workspace{Float64}) at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\COSMO\4kAZK\src\chordal_decomposition.jl:24
> [9] macro expansion at .\util.jl:213 [inlined]
 
> [10] optimize!(::COSMO.Workspace{Float64}) at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\COSMO\4kAZK\src\solver.jl:56
 
> [11] optimize!(::Optimizer) at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\COSMO\4kAZK\src\MOIWrapper.jl:155
 
> [12] optimize!(::MathOptInterface.Utilities.CachingOptimizer{Optimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\MathOptInterface\A2UPd\src\Utilities\cachingoptimizer.jl:189
 
> [13] optimize!(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Optimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}) at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\MathOptInterface\A2UPd\src\Bridges\bridge_optimizer.jl:225
 
> [14] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\MathOptInterface\A2UPd\src\Utilities\cachingoptimizer.jl:189
 
> [15] #optimize!#78(::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(optimize!), ::Model, ::Nothing) at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\JuMP\MsUSY\src\optimizer_interface.jl:141
 
> [16] optimize! at C:\Users\Lenovo\.juliapro\JuliaPro_v1.2.0-2\packages\JuMP\MsUSY\src\optimizer_interface.jl:111 [inlined] (repeats 2 times)

--------

**Comment by migarstka** [comment]
Hi Mark,
could you post the exact script that you use, so I can reproduce the error?

Seeing that the error happens as part of the chordal decomposition transformation, I would assume that a quick fix for now would be to use the alternative transformation or deactivate chordal decomposition.

a) Alternative transformation:
```julia
model = JuMP.Model(with_optimizer(COSMO.Optimizer, compact_transformation = false);
```

b) Deactivate decomposition:
```julia
model = JuMP.Model(with_optimizer(COSMO.Optimizer, decompose = false);
```

**Comment by markerror** [comment]
Mr migarstka, 
Thank you very much!
The errors vanish when I use the two models instead of the defeult settings. The obtained results are identical to the Mosek solver, especially that the first model go faster than the mosek's. Thanks again!

**Comment by migarstka** [comment]
That's good to hear :) 
Could you still post your code example so I can look what caused the initial error?

**Comment by markerror** [comment]
Thansk migarstka!
model = JuMP.Model(with_optimizer(COSMO.Optimizer, compact_transformation = false));
model = JuMP.Model(with_optimizer(COSMO.Optimizer, decompose = false));
The two models can work well, they get different results. I think there exist an unknown mistake.

Then I read the paper (COSMO: A conic operator splitting method for large convex problems) and  is confused, where the dual variable $\lambda$ in Eqs 9-10 vanishes in Eqs11,12,13,16 and Algorithm 1.

**Comment by markerror** [comment]
Thanks migarstka!
model = JuMP.Model(with_optimizer(COSMO.Optimizer, compact_transformation = false));
model = JuMP.Model(with_optimizer(COSMO.Optimizer, decompose = false));
The two models above can work well, yet they get different results. It is posible that there exist an unknown mistake.

Then I read the paper (COSMO: A conic operator splitting method for large convex problems) and is confused, where the dual variable $\lambda$ in Eqs 9-10 vanishes in Eqs11,12,13,16 and Algorithm 1.

**Comment by migarstka** [comment]
Hi Mark, 
the two models should return the same solution. If not there must be a bug in the solver code or the way you set up the problem. 
If you would post your code here, I could take a look. 😉

If you plug `(10b)` into `(10d)` you can see that it holds `lambda^k = 0 for all k`

**Comment by markerror** [comment]
Thanks. The code in my original example has many uncommented custom functions. I've listed another simple and different example below.

## A simple cone complementarity linearization algorithm (CCL)
using LinearAlgebra
using Test

 let
	m=3;
    solver="cosmo";
    ##build a cosmo+JuMP model by using JuMP.Model(with_optimizer(COSMO.Optimizer, compact_transformation = false,verbose=false));
	alpha=0.1;s=0.0;
    include("JuMP_Matlab.jl");# define some inteface functions are similar to the yalmip tool in MATLAB
	for s in propertynames(JuMP_Matlab)
	     eval(:($s=JuMP_Matlab.$s))
	end
	A0=[0 1 0 0 0 0;-1 0 1 0 0 0 ;0 0 0 1 0 0;1 0 -2 0 1 0;0 0 0 0 0 1;
	0 0 1 0 -1 0];
	B0=[0;1;0;0;0;0];
	C0=[0 0 0 0 1 0];
	n=size(A0,1);nu=size(B0,2);ny=size(C0,1);
	A=blkdiag(A0,zeros(m,m));#blockdiag
	B=[zeros(n,m) B0;eye(m) zeros(m,nu)];
	C=[zeros(m,n) eye(m);C0 zeros(ny,m)];
	B_=nullspace(B')';
	C_=nullspace(C);
    XX=rand(n+m,n+m);XX=XX'*XX;SS=inv(XX);
	OBJ=[10000.0];
	setlmi(solver);
	X=sdpvar(n+m);#define a JuMP variable X
	S=sdpvar(n+m);
	obj=[];
	Const=[-X,-S,-[X eye(n+m);eye(n+m) S],B_*(A*X+X*A'+2*alpha*X)*B_',C_'*(A'*S+S*A+2*alpha*S)*C_];
	for i=1:20
	    obj=trace(SS*X+XX*S);
	    s=solvesdp(Const,obj);#return the optimal value
	    XX=double(X);#return the value of the JuMP variable X
	    SS=double(S);
	    println("the optimal value is $s")
	    OBJ=[OBJ double(obj)];
		if s<2*(n+m)+0.0001 ##the value of s should be always larger than 2*(n+m)
			println("Find a feasible solution at the $i time!")
			break
		end 
	end
	setlmi(solver)
    K=sdpvar(size(B,2),size(C,1));
    AA=A+B*K*C;
    F=[AA'*SS+SS*AA+2*alpha*SS];
    @test solvesdp(F,[])<=0
    @test maximum(real(eigvals(double(AA))))<0
    real(eigvals(double(AA)))##these values should be smaller than -0.2
 end
##----------------------
##the above code need a user-defined Julia module file named after JuMP_Matlab
"define some functions are similar to the yalmip tool in MATLAB"
module JuMP_Matlab
	using LinearAlgebra
	using JuMP
	using COSMO

	export eye,setlmi,sdpvar,solvesdp,double,blkdiag,trace

	model=Model()
	eye(n::Int64)=Matrix{Float64}(I, n,n)# unix matrix

#initial a JuMP model
	function setlmi(solvername::String="Mosek")
		global model = JuMP.Model(with_optimizer(COSMO.Optimizer, compact_transformation = false,verbose=false));
	end

#define a symmetric JuMP variable
	sdpvar(n::Int64)=(n==1 ? @variable(model,) : @variable(model, [1:n,1:n],Symmetric))
	function sdpvar(m::Int64,n::Int64,r::Int64=1)
		if n==1
			return @variable(model,[1:m])
		elseif r==1
			return @variable(model,[1:m,1:n])
		else
			return @variable(model, [1:m,1:n,1:r])
		end
	end

#solve a JuMP model named model

	function solvesdp(cons,obj)
	    if obj==[]
            t=sdpvar(1)
			@constraint(model,t>=-1000.00)
	        @objective(model, Min, t)
	    else
            t=0.0;
	        @objective(model, Min, obj)
	    end	
	    for con in cons
	        if typeof(con)<:AbstractArray
	            @SDconstraint(model,con<=eye(size(con,1)).*t)
	        else
	            @constraint(model,con<=t)
	        end
	    end
	    optimize!(model)
	    return objective_value(model)
	end

	double(x)=value.(x)
	trace(A)=tr(A)

    blkdiag(A::Array,B::Array)=[A zeros(size(A,1),size(B,2));
            zeros(size(B,1),size(A,2))  B]
end

##-----get the following result at some time.

the optimal value is 236.14489332957874
the optimal value is 62.12888307726864
the optimal value is 33.306903034425986
the optimal value is 22.091526877157207
the optimal value is **17.247626222894**
Find a feasible solution at the 6 time!

##Note: the lastest value is 17.24 is smaller than 18, which is not possible theoretically (see more for the parper, El Ghaoui, L., F. Oustry, and M. AitRami. “A Cone Complementarity Linearization Algorithm for Static Output-Feedback and Related Problems.” IEEE Trans.Autom.Control 42, no. 8 (1997): 1171–76. https://doi.org/10.1109/9.618250).

And the same code can work correctly by using mosek and sedumi.
I think this error occur due to the  error accumulation.
