### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by bstellato** [oxfordcontrol/COSMO.jl#105]
It might be useful to have a python interface using pyjulia. 

This is a script that solves the LP from the documentation using python. I haven't managed to use sparse matrices though.

@spenrich

```python
# Use these two lines if you have anaconda, if you use pip
# just comment them and it should work
from julia.api import Julia
jl = Julia(compiled_modules=False)

# load cosmo
from julia import COSMO
import numpy as np

# LP data
n = 4
c = np.array([1, 2, 3, 4.])
A = np.eye(4)  # Haven't tried sparse matrices yet
I = np.eye(n)
b = np.array([10, 10, 10, 10])

# define constraints
# -------------------
# Ax <= b
c1 = COSMO.Constraint(-A, b, COSMO.Nonnegatives)
# x >= 1
c2 = COSMO.Constraint(I, -np.ones(n), COSMO.Nonnegatives)
# x2 >= 5
c3 = COSMO.Constraint(np.array([0, 1, 0, 0]), -5, COSMO.Nonnegatives)
# x1 + x3 >= 4
c4 = COSMO.Constraint(np.array([1, 0, 1, 0]), -4, COSMO.Nonnegatives)


# define cost function
# -------------------
P = np.zeros((4, 4))
q = c

# assemble solver model
# -------------------
settings = COSMO.Settings(max_iter=2500, verbose=True, eps_abs = 1e-4, eps_rel = 1e-5)
model = COSMO.Model()
COSMO.assemble_b(model, P, q, [c1, c2, c3, c4], settings = settings)
res = COSMO.optimize_b(model)
x = res.x
```

**Comment by migarstka** [comment]
Thanks @bstellato for the example. 
I agree, it would be good to have a python interface to provide access to the solver to a wider user base.

Even if there is no support for direct conversion of a Python-sparse-matrix to a Julia-sparse-matrix. This could be handled fairly easy by the interface.

**Comment by migarstka** [comment]
It seems one could make a hacky solution to call `COSMO` from R as well. Using this R-package:
https://github.com/Non-Contradiction/JuliaCall

**Comment by migarstka** [comment]
This might be relevant as well: https://julialang.github.io/PackageCompiler.jl/dev/apps/

**Comment by akshayka** [comment]
Gently pinging this issue -- are there any plans to add a Python interface?

The [CVXPY](https://github.com/cvxgrp/cvxpy) developers (@SteveDiamond, @bstellato, @rileyjmurray) are interested in adding `COSMO.jl` as a solver. We can handle the reduction from CVXPY problems to `COSMO`'s standard form, but a Python interface supporting sparse matrices would make it much easier for us to actually invoke `COSMO`.

**Comment by migarstka** [comment]
@akshayka Thanks for offering your help. Much appreciated! 😃

This gets requested more and more and it would be great to have an interface to the modelling tools in CVXPY. 
I think a first step **from our side** is to make a repository, similar to [osqp-python](https://thepiratebay.org/) and/or [scs-python](https://github.com/bodono/scs-python) to just expose the bare functionality: initialise a model, set the data, solve. This would give **you** something to work with.

In terms of sparse matrices, does CVXPY use `scipy.sparse` or its own implementation?

**Comment by migarstka** [comment]
@akshayka I managed to get a basic COSMO python-interface working:
https://github.com/oxfordcontrol/cosmo-python

One missing part I haven't exposed yet is the ability to pass box-constraints, but I guess this can be added at a later stage.

I haven't set up package building or CI yet, but it should give you something to work with. Let me know if you need any help with the CVXPY integration, write access to the repo, etc.

**Comment by akshayka** [comment]
Awesome, thanks!! It'll be great to have COSMO in CVXPY. I'll let you know if we run into any issues.

**Comment by yangbo116** [comment]
Is there any method such that COSMO can be called through Python interface with PardisoDirectKKTSolver, I find that the solver can solve the linear system through QdldlKKTSolver, CholmodKKTSolver on Python but filed through PardisoDirectKKTSolver. It can be solved on Julia by using Pardiso.
