### ISSUE TITLE
First-solve time vs precompilation time

### ISSUE THREAD

**Issue by ericphanson** [oxfordcontrol/COSMO.jl#108]
I spent a bit of time today looking into using SnoopCompile to generate precompile statements which could speed up "first solve" times: https://gist.github.com/ericphanson/959210a4c44900f2f379a805a0aa3d7c. (I thought it would be nice to make COSMO the solver for the example in the Convex.jl README, but I didn't want a slower first-solve experience for newcomers, and SCS has the advantage of only needing compilation for the wrapper). The takeaway I had was that the first-solve time could be sped up by 15-25 seconds via precompile statements, at the cost of ~25 seconds of additional precompilation, and ~3 seconds of `using` time. I'm not entirely sure that's worth the tradeoff, so I haven't opened a PR, but the `precompile` branch of my fork https://github.com/ericphanson/COSMO.jl has the statements. Let me know if you'd like a PR.

Just for clarity, the relevant times are:
* Precompilation, which happens when a new version is released (or possibly a new version of a dependency?). That's when you get the `precompiling...` message
* `using` time: this is `@time using COSMO` once it's been precompiled
* "first-solve" time, which I've been testing via `@time solve!(problem, COSMO.Optimizer(verbose=false)` using the Convex.jl problem from its README

The increase in `using` time surprised me, so I opened an issue https://github.com/timholy/SnoopCompile.jl/issues/74 to ask about it.

**Comment by mlubin** [comment]
If we assume that: 
- precompilation happens rarely, and users don't expect it to be fast
- most of the time when the package is imported via `using`, you actually use it

Then I think this is a clear win.

**Comment by migarstka** [comment]
Thanks for looking into this @ericphanson 
I think it's a good idead to reduce the "first solve time" of COSMO, especially when it's used in a short example.
I agree with @mlubin that your proposed change is a reasonable trade-off. Can you open a PR?
