### ISSUE TITLE
Invalid equation in README

### ISSUE THREAD

**Issue by blegat** [oxfordcontrol/COSMO.jl#110]
![invalid_eq](https://user-images.githubusercontent.com/1048205/77450964-5264b180-6df4-11ea-98dc-2e7506bb31eb.png)

**Comment by migarstka** [comment]
thanks @blegat 

That seems to be Browser dependent. Works for me with Firefox, but not with Safari

**Comment by migarstka** [comment]
Fixed 0998fd69f8ab83c484ae6018215a07bcc947b899
