### ISSUE TITLE
questions about the logistic regression example

### ISSUE THREAD

**Issue by rafreeman** [oxfordcontrol/COSMO.jl#111]
These questions concern the example in the file `examples/logistic_regression_regularization.ipynb`:

1. The contour plot looks at the level set where the z variable takes on the value of 0.5.  But z is the dot product of theta and x, which is not the probability.  Instead, the probability is g(z)=1/(1+exp(-z)).  So shouldn't we instead be plotting the level set z=0 instead of z=0.5?  This would give a probability of g(0)=0.5.  It also seems to look like a better classifier curve for the data (although looks can be deceiving).

2. In the section "Defining the logistic model," the objective J(theta) is the likelihood plus the regularization term.
But does it make sense to add the regularization term to the likelihood?  Doing so makes the solution of the maximization problem theta=infinity.   In contrast, in the code the objective is the log likelihood plus the same regularization term, which I think is the correct version.  So should we change J to be the log likelihood plus the regularization (and change the maximize to minimize)?

**Comment by migarstka** [comment]
Hi @rafreeman,

you are right about both questions. Thank you for pointing them out. 
I fixed them and moved the example to the Documentation:
https://oxfordcontrol.github.io/COSMO.jl/dev/examples/logistic_regression/

**Comment by rafreeman** [comment]
Thanks for the updates on this nice example.  One more minor correction: we want to add the regularization term to -J (the **negative** of the log likelihood) and turn the maximization into a minimization.  So instead of solving "maximize J(theta) + mu||theta||" we should solve "minimize -J(theta) + mu||theta||" which is what the code is actually doing.  Again the code seems correct, the typos are just in the description.  Also, I think the usual spelling is "likelihood" not "likelyhood" (the description uses both versions).

**Comment by migarstka** [comment]
Fixed here: 9cdd8562e66096594fd0fa6d2bb3961a03f6bf40
Many thanks.
