### ISSUE TITLE
Issue with MOI master

### ISSUE THREAD

**Issue by blegat** [oxfordcontrol/COSMO.jl#116]
See https://travis-ci.com/github/blegat/SolverTests/jobs/380241587#L510
and https://travis-ci.com/github/blegat/SolverTests/jobs/380241587#L539
The second issue is due to the use of the `_pass_attributes` internal function that changed its signature in https://github.com/jump-dev/MathOptInterface.jl/pull/1121/

**Comment by blegat** [comment]
I have updated the version number of the Project.toml on MOI master, so that you can use it to either branch in the code and call a different signature or simply require this new version in Project.toml.

**Comment by migarstka** [comment]
Thank you for the heads-up @blegat.

I changed the code in COSMO to account for the changes in `_pass_attributes` here: https://github.com/oxfordcontrol/COSMO.jl/commit/92a6fbca57ff5da9f3e993d1804b05193f7575f9

I guess I will wait until you release MOIv0.9.15 and then tag a new release for COSMO that requires that new version.

**Comment by blegat** [comment]
Supporting names is quite easy. The code in `Utilities/model.jl` is written such that it's easy to reuse by calling (non-internal) methods.
You can check `Utilities/universalfallback.jl` to see how to reuse these

**Comment by blegat** [comment]
MOI was release, I would recommend releasing a new version of COSMO asap as the current one is failing.

**Comment by migarstka** [comment]
I added the changes as discussed 8b377b6a52ce3d636e10096f4766b965d6a353d7. New version will be tagged once the CI tests pass.
