### ISSUE TITLE
Bump compat bounds for DataStructures.jl

### ISSUE THREAD

**Issue by imciner2** [oxfordcontrol/COSMO.jl#118]
DataStructures.jl has released a new 0.18.x version in August, and I believe that the fact COSMO.jl only has a compat bound for 0.17.x is causing package compatibility issues on my Julia install.

**Comment by blegat** [comment]
Could we get a new release ? :)

**Comment by migarstka** [comment]
registered here: https://github.com/JuliaRegistries/General/pull/25077
