### ISSUE TITLE
Add MATLAB interface for COSMO

### ISSUE THREAD

**Issue by Mark-L-Stone** [oxfordcontrol/COSMO.jl#128]
I would like a capability to call COSMO from MATLAB. Perhaps this could be accomplished by building a CMEX file for COSMO. This should then enable YALMIP, among other optimization modeling tools, to add COSMO as an available solver.

Note the related request https://github.com/cvxgrp/cvxpy/issues/1161 to add COSMO as an available solver under CVXPY.

**Comment by Mark-L-Stone** [comment]
Is there any update on this?

**Comment by migarstka** [comment]
Won't be working on this anytime soon. Contributions always welcome. Closing for now!
