### ISSUE TITLE
Warm starting issue through Convex.jl ? 

### ISSUE THREAD

**Issue by lrnv** [oxfordcontrol/COSMO.jl#135]
Hi, 

On last versions of COSMO, Convex and MathOptInterface, I am trying to warm start a BigFloat problem with the solution of the same problem on standard precision, through the following code: 

```julia
using Convex, COSMO
y = Variable(3);
x = [1.0,2,3];
p = minimize(Convex.norm(y - x,2) + Convex.norm(y,1));
solve!(p, () -> COSMO.Optimizer(verbose=true),warmstart=true)

# Starting objective value : -4.001e+01
# Stoping objective value : 3.7417e+00

# Now find a better value with bigfloats (or other multi-precision type)
BigType = BigFloat;
x = BigType.(x);
eps = BigType("1e-50");
set_value!(y,BigType.(Convex.evaluate(y)));
p = minimize(Convex.norm(y - x,2) + Convex.norm(y,1); numeric_type = BigFloat);
solve!(p, () -> COSMO.Optimizer{BigType}(verbose=true,eps_abs=eps,eps_rel=eps),warmstart=true)

# Starting objective value : -4.001e+01
# Stoping objective value : 3.7417e+00 (greater precision in primal and dual res)
```

If i omit the `numeric_type = BigFloat`, i have an error, [see this discourse thread](https://discourse.julialang.org/t/arbitrary-precision-refinnements-with-convex-jl-cosmo-jl/61806) telling me that indeed Convex is trying to use the warm start functionality in COSMO. 

But when using the right call, it seems like, from COSMO outputs, that the warm starting did not change anything: the model re-started from the same objective, primal res and dual res. 

Do i need to do something else to warm start the model ?

**Comment by migarstka** [comment]
I will close and refer to the discussion on discourse: https://discourse.julialang.org/t/arbitrary-precision-refinnements-with-convex-jl-cosmo-jl/61806/8
