### ISSUE TITLE
Confused by the "Optimal objective" reporting

### ISSUE THREAD

**Issue by ShuhuaGao** [oxfordcontrol/COSMO.jl#138]
Hi, 

Thanks for offering this solver. When solving a toy QP problem via the `JuMP` interface, I noticed the following issue. Does the "optimal objective" reported by COSMO refer to the optimal objective function value? It differs from the one told by JuMP.
![image](https://user-images.githubusercontent.com/20141984/125157743-3038a380-e19f-11eb-9191-6638a73e6001.png)

I solved the problem with Gurobi again and validated that 100.605 is the minimum objective value.

**Comment by migarstka** [comment]
Hi @ShuhuaGao, does your problem objective have a constant term?
If not, please post a minimum working example for me to reproduce the problem.

The printed optimal objective is the objective of the internal problem passed to `COSMO` by `JuMP`. Before `COSMO` solves the problem, JuMP might do some problem transformations. 

An easy way to see this is to solve a maximization problem in JuMP. COSMO's standard form only does minimization, so JuMP will flip the sign of the objective before passing the problem to COSMO. In COSMO's output you will see that the optimal objective displayed is equal to -1 * the objective reported by JuMP.

**Comment by ShuhuaGao** [comment]
@migarstka Thanks for the explanation. It makes sense. There are indeed constant terms in the objective.

However, when I use Gurobi as the solver in JuMP, Gurobi reports the original objective value (including the constant). Gurobi may be treated differently.

**Comment by migarstka** [comment]
I am assuming JuMP passes the constant to Gurobi which then adds it to their internal objective. 
Thank you for raising this. I see how the raw output can lead to confusion.
I will think about adding the constant offset  to COSMO.
