### ISSUE TITLE
Question about solve time wrt dimension

### ISSUE THREAD

**Issue by JinraeKim** [oxfordcontrol/COSMO.jl#145]
While I read [the COSMO.jl paper](https://arxiv.org/pdf/1901.10887.pdf),
I was curious about "why the solve time decreases as the dimension increases" in the case of COSMO up to `n = 150`:
![image](https://user-images.githubusercontent.com/43136096/145569109-b0ca322d-db31-4e7e-8257-b6460efdfb6f.png)

How is it possible?

**Comment by JinraeKim** [comment]
Or, such phenomenon is it often reported from the literature?

**Comment by migarstka** [comment]
Hi @JinraeKim, thanks for noticing this. At small dimensions, where the linear system solve step dominates the computation time, I did in fact notice some variance in the solve time. The results here are from a single run of the problem set on the compute cluster. Running the same problem set multiple times and averaging the solve times should show a more congruent impact of the problem dimension on the solve time.

**Comment by JinraeKim** [comment]
> Hi @JinraeKim, thanks for noticing this. At small dimensions, where the linear system solve step dominates the computation time, I did in fact notice some variance in the solve time. The results here are from a single run of the problem set on the compute cluster. Running the same problem set multiple times and averaging the solve times should show a more congruent impact of the problem dimension on the solve time. 

Thank you.
Do you think it's possible from the mean values from multiple runs?
Actually, I observed this phenomenon in my case with 500 runs, so I'm inspecting the reason :)

**Comment by migarstka** [comment]
If it is systematically slower, could you send me a MWE version of the script via email or post it here? Would be interesting to see.

**Comment by JinraeKim** [comment]
Ah, it's not actually run with COSMO.jl for now, but I found that this phenomenon is observed when solver = COSMO.
