### ISSUE TITLE
Custom convex set vs convex cones?

### ISSUE THREAD

**Issue by matbesancon** [oxfordcontrol/COSMO.jl#147]
The tutorial is unclear on which types of convex sets are supported, whether they need to be cones or can be convex sets with a projection operation defined: 
https://oxfordcontrol.github.io/COSMO.jl/stable/literate/build/custom_cone/#Cone-definition-and-projection-function

**Comment by migarstka** [comment]
Thanks for pointing this out @matbesancon 

The API and the tutorial are designed with convex cones in mind, so I changed it for consistency here: d92a15bd5e3656dcb031dbc4950b7b1e41efdcf9

In principle, it works with any convex compact set, e.g. Hyperbox.
