### ISSUE TITLE
SVM example in documentation throws many warnings in output

### ISSUE THREAD

**Issue by goulart-paul** [oxfordcontrol/COSMO.jl#150]
The SVM example at https://oxfordcontrol.github.io/COSMO.jl/v0.8/examples/svm_primal/ is showing many errors in the autogenerated output.  This issue seems to have started with v0.8, since the v0.7 documentation at https://oxfordcontrol.github.io/COSMO.jl/v0.7/examples/svm_primal/ looks fine.

**Comment by migarstka** [comment]
It's a problem with one of the dependencies, see here: https://github.com/JuliaStats/StatsFuns.jl/issues/121

**Comment by devmotion** [comment]
The problem was fixed more than a year ago and should not occur with StatsFuns >= 0.9.9. The issue seems to be that some dependency pulls in StatsFuns 0.9.7: https://github.com/oxfordcontrol/COSMO.jl/actions/runs/2897741705/jobs/4609456933#step:4:377

**Comment by migarstka** [comment]
This took me a long time to figure out.

StatsFuns stayed on 0.9.7 in the GH action no matter how I changed the dependency requirements. Turns out I had the GH action configured to run with Julia v1.4 which forced the dependency. Should be resolved with 39ce661
