### ISSUE TITLE
can't install COSMO & Clarabel.jl together

### ISSUE THREAD

**Issue by Sage0614** [oxfordcontrol/COSMO.jl#161]
COSMO & Clarabel both depends on QDLDL where COMSO requires QDLDL version <0.3 and Clarabel requires a version >=0.3, is this on purpose or both can work with latest version of QDLDL?

https://github.com/oxfordcontrol/COSMO.jl/blob/80085a9ad47b65203f8495976b5e77811a7fd082/Project.toml#L31
https://github.com/oxfordcontrol/Clarabel.jl/blob/7d7f99a13f0f4642a15514f2ed30363e315cc35c/Project.toml#L27

Thanks,
Song

**Comment by migarstka** [comment]
I need to adapt the  code  to make  it compatible to QDLDL v0.3. You can use different julia environments to install the solvers in, or do you need them side-by-side in the same environment?

**Comment by goulart-paul** [comment]
I did not realise that this was an issue.   I can have a look as well.

I am reasonably (?) sure that QDLDL v0.3 hasn't done anything weird to break COSMO, but perhaps there is some minor interface change.

**Comment by migarstka** [comment]
Was fixed in 724a2d2 and will be available in new version 0.8.7
