### ISSUE TITLE
Passing attributes error in JuMP/MOI wrapper

### ISSUE THREAD

**Issue by Amuwa** [oxfordcontrol/COSMO.jl#168]
When a JuMP/MOI model has a name attribute, which can be accessed by `MOI.get(model, MOI.Name())`, the function `pass_attributes!()` in `MOI_wrapper.jl` fails with "unsupported attribute".

To fix this, I tried to append `&& attr != MOI.Name()` to line 561 of `MOI_wrapper.jl`, and it works.

Hope the bug get fixed in the incoming update.

**Comment by Amuwa** [comment]
I just create a pull request for this bug

**Comment by migarstka** [comment]
Could you post a minimal working example of a model that produces the error?
