### ISSUE TITLE
Error in indirect KKT solver: `tol` keyword in IterativeSolvers.jl deprecated

### ISSUE THREAD

**Issue by tjdiamandis** [oxfordcontrol/COSMO.jl#179]
https://github.com/oxfordcontrol/COSMO.jl/blob/4144def604a7d814c44968480847a459d38bb5ce/src/linear_solver/kktsolver_indirect.jl#L70

Should be replaced with `reltol` or `abstol` (https://iterativesolvers.julialinearalgebra.org/stable/linear_systems/cg/#CG).

I assume that `reltol` is preferred here?

**Comment by goulart-paul** [comment]
Good question.   It's not clear to me whether it should be `abstol` or `reltol` there.   Note that a few lines below we have :
https://github.com/oxfordcontrol/COSMO.jl/blob/4144def604a7d814c44968480847a459d38bb5ce/src/linear_solver/kktsolver_indirect.jl#L73
   
where the tolerance is divided by the initial residual.   Given the documentation for `cg!` takes as a convergence test `|r_k| ≤ max(reltol * |r_0|, abstol)` (see [here](https://iterativesolvers.julialinearalgebra.org/stable/linear_systems/cg/#IterativeSolvers.cg!)), it's not really clear to me what we are expecting to happen.

Another problem in the same place is that we probably shouldn't be normalizing by `norm(y1)` without some guard against a zero norm condition, i.e. something like `max(norm(y1),1.)` seems safer.

Not sure who wrote this originally - paging @migarstka and @nrontsis...

**Comment by tjdiamandis** [comment]
Ah good point. I mean that changing to `reltol` would give the same behavior as you had previously. However, it looks like use `abstol` should be used directly and the normalization should be removed since `IterativeSolvers.jl` multiplies by the norm of the initial residual?

Compare https://github.com/JuliaLinearAlgebra/IterativeSolvers.jl/blob/c91cfbc5e80c4451d4b0c7bc9433e5302915cccc/src/cg.jl#L141

with 
https://github.com/JuliaLinearAlgebra/IterativeSolvers.jl/blob/49cc093d60babbf7a3edd0119958d93617771406/src/cg.jl#L132

(also the warning in v0.8)
https://github.com/JuliaLinearAlgebra/IterativeSolvers.jl/blob/152f89f39db9c693cf283a8dc7b6c75be0499200/src/cg.jl#L134

**Comment by migarstka** [comment]
> Not sure who wrote this originally - paging @migarstka and @nrontsis...
```
$ git blame -L70 -- src/linear_solver/kktsolver_indirect.jl
```
```
8553294f src/kktsolver_indirect.jl (nrontsis     2019-09-02 17:55:25 +0100  70)         cg!(S.previous_solution, L, y1, tol=get_tolerance(S)/norm(y1))
```
One for you @nrontsis 😋

I think we should aim to support the latest stable release of IterativeSolvers.jl which seems to be v0.9+ and also add that constraint to the dependency file.

I would go with:

```julia
cg!(S.previous_solution, L, y1, atol=get_tolerance(S)/max(norm(y1),1.))
```
Is anyone willing to create a PR for this? We should also check whether the basic tests [here](https://github.com/oxfordcontrol/COSMO.jl/blob/master/test/UnitTests/kktsolver.jl) actually run.

**Comment by nrontsis** [comment]
I think this was a hack to [get around an issue of `IterativeSolvers.jl` at the time](https://github.com/JuliaLinearAlgebra/IterativeSolvers.jl/pull/244).

I think we should go with:
> (...abstol=get_tolerance(S), reltol = 0.)

that Paul suggested. Having this with `IterativeSolvers.jl` 0.9+, might actually not be a breaking change as compared to the behaviour I had when [I committed the line under question](https://github.com/oxfordcontrol/COSMO.jl/blob/4144def604a7d814c44968480847a459d38bb5ce/src/linear_solver/kktsolver_indirect.jl#L70) (`8553294f`), unless when `|r_0| = 0`. I can write a simple "test" that checks this on toy data.

**Comment by migarstka** [comment]
Closed with PR above
