### ISSUE TITLE
Outdated note in the docs about JuMP not supporting arbitrary precision

### ISSUE THREAD

**Issue by blegat** [oxfordcontrol/COSMO.jl#184]
The note here:
https://oxfordcontrol.github.io/COSMO.jl/stable/literate/build/arbitrary_precision/
is outdated as JuMP now supports arbitrary precision (as of v1.13)

**Comment by migarstka** [comment]
Thanks for flagging this. I'll adapt this.

**Comment by migarstka** [comment]
#188
