### ISSUE TITLE
Implement Acceleration schemes

### ISSUE THREAD

**Issue by migarstka** [oxfordcontrol/COSMO.jl#19]
- understand fixed point acceleration

**Comment by angeris** [comment]
Of possible interest here, we have some people from our group working on accelerated schemes for `SCS` and now has a [C package available](https://github.com/cvxgrp/aa) (if you're interested, I could make some Julia bindings.)

Additionally, [SCS](https://github.com/cvxgrp/scs) now has it on by default and it works fairly well, so might be a good reference!

**Comment by migarstka** [comment]
Thanks for offering. We are currently investigating different approaches for acceleration. It will likely be modular so that the user can choose the acceleration method. Once a stable interface for this has been established I might pick you up on that offer.

**Comment by angeris** [comment]
Sounds great! Let me know :)

**Comment by migarstka** [comment]
Implemented in latest version v0.8.0

**Comment by angeris** [comment]
Awesome, this is great ! I (again) have some big SDPs to solve that are very structured, so will try them with COSMO :)

**Comment by angeris** [comment]
Thanks for all of your work on this!
