### ISSUE TITLE
Support for the complex PSD cone

### ISSUE THREAD

**Issue by araujoms** [oxfordcontrol/COSMO.jl#193]
Are you interested in adding direct support for the complex PSD cone? It's much faster than solving a complex problem via the embedding in the real PSD cone.

Currently the only solver that has it is [Hypatia](https://github.com/jump-dev/Hypatia.jl), so it'd be great to have a first-order solver that supports it as well.

**Comment by migarstka** [comment]
Hi @araujoms,

Yes, I think this would be a neat improvement if there is demand and application for this feature :) Are you offering to implement it or would you use it?

**Comment by araujoms** [comment]
I would definitely use it. I could implement it. I mean, the algorithmic part is trivial, the implementation is mostly about choosing how to represent complex matrices and integrate them with the rest of the codebase.
