### ISSUE TITLE
Implement vanilla CG and test in benchmark problems

### ISSUE THREAD

**Issue by nrontsis** [oxfordcontrol/COSMO.jl#29]
We want to test CG on problems that are quite big, as this it only makes sense to use CG in those cases.

We would also want to apply to a challenging, ill conditioned dataset that will allow us to compare e.g. preconditioners. #30 is perhaps suitable.

**Comment by goulart-paul** [comment]
Fixed support for CG solvers in #107

**Comment by nrontsis** [comment]
Should we close then?

**Comment by goulart-paul** [comment]
If you're happy to do so, then yes.   I think you were the one who wrote the CG (reduced) and MINRES indirect solvers.  Both seem to work, but maybe you had some additional feature in mind with this.
