### ISSUE TITLE
Complete box constraint implementation

### ISSUE THREAD

**Issue by migarstka** [oxfordcontrol/COSMO.jl#55]
In order to support the box constraint with _infeasibility detection_ and _scaling_, we have to implement some of the functions in `src/convexset.jl`

- `in_dual()`: Right now this seems only to check whether a vector is outside the box
- `in_recc()`: Evaluates always to true
- `scale!()`: Multiplies the box boundaries with a `SplitVector`. What was the rational behind that @goulart-paul

**Comment by migarstka** [comment]
#61

**Comment by goulart-paul** [comment]
https://github.com/oxfordcontrol/COSMO.jl/pull/62 instead.

**Comment by migarstka** [comment]
Implemented in 6a4d93e2937c345bee098f84862651c993354f2a
What remains to be done is a merging step for multiple constraint that result in ZeroSet, Nonnegatives, Box when the problem is formulated via MOI

**Comment by blegat** [comment]
> What remains to be done is a merging step for multiple constraints that result in ZeroSet, Nonnegatives or Box when the problem is formulated via MOI

cc @chriscoey I remember you were also interested in having all the Nonnegatives constraint grouped together (but I cannot find the issue in MOI where we discussed it)

**Comment by chriscoey** [comment]
I do this merging in Hypatia. @migarstka I'll add you to the repo

**Comment by migarstka** [comment]
@blegat The question is if this merging belongs to MOI or should be done by each solver wrapper individually. I guess solvers that support the standard cones do this implicitly by sorting the constraints and then constraining consecutive elements  of the constraint primal variable to be in the zero cone, nonnegative orthant, etc... (like SCS)

@chriscoey Thank you. I'll take a look.

Apart from this discussion I still think it would be useful to have the Box (higher-dimensional intervall) as an available constraint set in MOI.

**Comment by chriscoey** [comment]
Hypatia can handle a multidimensional box with a single L_inf norm epigraph (conic) constraint. So there's a question of whether MOI have the box set or the box cone or both

**Comment by blegat** [comment]
I wouldn't be against adding a multidimensional box. Users may want to model with that (e.g. having the state belong to an hyperrectangle is useful in Control), and solvers supports it so it makes sense to add it to MOI.

Grouping constraints of the same cone together is what is currently done by ECOS, SCS, SeDuMi, CDCS in their wrappers, there is plan to make a utility for that, see https://github.com/JuliaOpt/MathOptInterface.jl/issues/24#issuecomment-459976479
