### ISSUE TITLE
Sympacked U vs sympacked L

### ISSUE THREAD

**Issue by blegat** [oxfordcontrol/COSMO.jl#66]
In the MOI wrapper code, it seems that there is some conversion done with the `sympackedUtoL` and `sympackedLtoU` functions between "upper triangular column-wise" and "lower triangular column-wise" as is done in the SCS wrapper.
However, in the COSMO do, it is written that the PsdConeTriangle of COSMO is "upper triangular column-wise" which is the same than MOI so where is there conversion done ? I am surprised that it works for PSD matrices of size larger than 2.

**Comment by migarstka** [comment]
Yes, I think this is a bug. The only line where `sympackedLtoU` is used is in
https://github.com/oxfordcontrol/COSMO.jl/blob/549c95e82b0120f0d5e89016b22560b05054a782/src/MOIWrapper.jl#L281
and the only line where `orderval` is used is in processing constraints where `f::MOI.VectorOfVariables`

https://github.com/oxfordcontrol/COSMO.jl/blob/549c95e82b0120f0d5e89016b22560b05054a782/src/MOIWrapper.jl#L422

The reason why this doesnt create any unforeseen results is that in that line a vector of 1's is reordered which doesnt make sense but also doesnt change anything.

I will remove all those helper functions and the unnecessary `orderval` in line 422
