### ISSUE TITLE
Tests do not pass on 1.2 branch of julia

### ISSUE THREAD

**Issue by KristofferC** [oxfordcontrol/COSMO.jl#83]
While running tests on all package for the upcoming Julia 1.2 release, this package started failing with the error:

```
QP - Lasso: Test Failed at /root/.julia/packages/COSMO/7ALGG/test/UnitTests/qp-lasso.jl:42
  Expression: isapprox(res.obj_val, 46.40521553063313, atol=0.001)
   Evaluated: isapprox(45.609486486081586, 46.40521553063313; atol=0.001)
```

The cause of failure was bisected to the PR https://github.com/JuliaLang/julia/pull/30494 which improved the performance of random numbers for sparse matrices but also changed the exact numbers that got generated.

**Comment by migarstka** [comment]
This test seems to be failing because of the way random matrices are generated changed. 
Will this change to the random number stream be kept in Julia v1.2?

If yes, we could just hardcode the problem data instead of randomly generating it.

**Comment by KristofferC** [comment]
> This test seems to be failing because of the way random matrices are generated changed.

Yes.

I am personally not 100% sure what the exact policy is regarding backwards compatibility of the random number streams. I know at least that we won't change them in patch version. Best if possible not to rely on he exact random numbers of course.

**Comment by migarstka** [comment]
I removed the test problem since it was redundant anyway. 660fb7f
