### ISSUE TITLE
Shared memory for multiple cones of the same type

### ISSUE THREAD

**Issue by migarstka** [oxfordcontrol/COSMO.jl#84]
It would be helpful to allow multiple cones to share the same workspace during the projection. Right now every cone pre-allocates the memory necessary during its projection. However, assuming the dimension of the cones are the same (as for exponential cones) and the projections are carried out sequentially there is no need for every cone to allocate its own temporary workspace variables. Instead  one set of variables should be used by all the cones

**Comment by goulart-paul** [comment]
I thought that the goal of giving every cone its own memory space was to:

1) Allow for parallel projection at some point in the future, and 
2) To allow us to use inexact/iterative factorisation methods for the PSD cone, where each projection would need to carry its own internal state.

If you really want to have a shared memory space for the exponential cones, then wouldn't it be better to just define a multivariate / vectorized exp cone type?
