### ISSUE TITLE
Return dual objective function

### ISSUE THREAD

**Issue by migarstka** [oxfordcontrol/COSMO.jl#89]
Support `DualObjectiveValue` in new MOI v0.9.

Similar to the discussion in OSQP repo:
https://github.com/oxfordcontrol/osqp/issues/175

**Comment by gbanjac** [comment]
The dual problem can be written as

![dual](https://user-images.githubusercontent.com/10811644/92212970-1483b300-ee93-11ea-9b0c-5308a06a7362.png)

If you already have a routine for computing the eigenvalue decomposition, then you should be able to compute the dual objective value given `y`.
