### ISSUE TITLE
Support MOI.get(optimizer::Optimizer, ::MOI.DualObjectiveValue)

### ISSUE THREAD

**Issue by guilhermebodin** [oxfordcontrol/COSMO.jl#91]
Hello, 

I am currently working on Dualization.jl and I use COSMO as one of the solvers to test. One of the features is to dualize a model and solve it and return the primal solution, but for that, I query the DualObjectiveValue. Is it possible to add it to the results struct?

**Comment by blegat** [comment]
Seem to be a duplicate of https://github.com/oxfordcontrol/COSMO.jl/issues/89

**Comment by guilhermebodin** [comment]
Indeed! Thanks @blegat
