### ISSUE TITLE
NLPBlock appears to be ignored

### ISSUE THREAD

**Issue by mlubin** [oxfordcontrol/COSMO.jl#97]
An error should be thrown if there's an `NLPBlock` in the input. See https://discourse.julialang.org/t/jump-not-getting-the-correct-solution-of-the-optimization-problem/29947.

**Comment by migarstka** [comment]
This is mainly caused by the fact that we use our own model copying functions (which up to this point ignore any unknown MOI.attruibutes) rather than switching to the MOI `allocate-load` - interface.

**Comment by migarstka** [comment]
Resolved  by 39d7bc1c7a54214
